### PR TITLE
Fix error messages for raincloud plots

### PR DESCRIPTION
**Pull request by maltelueken**
Fixes jasp-stats/INTERNAL-jasp#1478
Fixes jasp-stats/INTERNAL-jasp#1465
Fixes jasp-stats/jasp-test-release#1478
Fixes jasp-stats/jasp-test-release#1479

Adds:
- error checks and messages
- help file entries

for all t-test raincloud plots

### CODE REVIEW

**Comment by Kucharssim** [comment]
Can you add GITHUB_PAT to fix the unit tests? See https://github.com/jasp-stats/jaspSem/blob/8df648031fed28a692600e39de23a0f0a262618b/.github/workflows/unittests.yml#L23 for an example

**Review by Kucharssim — CHANGES_REQUESTED** [review]
The issues are fixed. I left a minor comment in the code. I wonder whether you could reduce the code duplication somewhat, but it's not a big deal.

The tests pass on my computer, but I would like to merge this after they pass here as well.

**Comment by maltelueken** [comment]
I have the checks in every single t-test function because they all specify the dependent variable differently. I agree that it would be easier to have the error checks only once, but then I would need to rewrite all the functions as well and this might also interfere with the ANOVA module where the function is used too. So, I though this is easier (and it's similar to the normal descriptive plots).

**Comment by maltelueken** [comment]
I think it might also be worth it to fix jasp-stats/jasp-test-release#1478 and jasp-stats/jasp-test-release#1479 in this PR. I will look at these tomorrow!

**Review by Kucharssim — APPROVED** [review]
Great work! Nice that you were able to reuse the errors function.

**Pull request merged**
