### PR TITLE
import functions from jaspAnova

### PR DESCRIPTION
**Pull request by vandenman**
Fixes https://github.com/jasp-stats/jaspTTests/issues/9 (Part 2)

- imports `summarySE` and `summarySEwithin` from jaspAnova.

this only works when checking out https://github.com/jasp-stats/jaspAnova/pull/12 simultaneously.

### CODE REVIEW

**Comment by vandenman** [comment]
the unit tests will probably fail because `jaspAnova` doesn't export the functions yet.

**Comment by vandenman** [comment]
@TimKDJ I think this is ready for another review

**Review by TimKDJ — APPROVED** [review]

**Comment by TimKDJ** [comment]
Did the unit test fail come from this PR?

**Comment by vandenman** [comment]
@TimKDJ the unit tests failed because the changes to the test file in https://github.com/jasp-stats/jasp-desktop/pull/4286/files were not added to this repo.

**Pull request merged**
