### PR TITLE
Delete ttestplotfunctions.R

### PR DESCRIPTION
**Pull request by vandenman**
While looking at https://github.com/jasp-stats/jasp-test-release/issues/1523, @JorisGoosen got pretty confused because he was looking at old unused functions such as `.plotSequentialBF.ttest`, which are just terrible to look at (they're very long).

I deleted all functions that I think are unused. Here is a table of the new function names (if they exist).

| old name | new name |
| -------- | -------- |
`.plotSequentialBF.ttest` | `.plotSequentialBF.ttest2` 
`.plotBF.robustnessCheck.ttest` | `.plotBF.robustnessCheck.ttest2`
`plot2GroupMeansBayesIndTtest`| not used anywhere (the comment is a lie)
`.plotGroupMeanBayesOneSampleTtest` | not used anywhere

### CODE REVIEW

**Comment by TimKDJ** [comment]
For my understanding, why did these still exist? Were they still used for a time?

**Comment by vandenman** [comment]
> Were they still used for a time?

Yes, when I rewrote the Bayesian t-tests to jaspResults. I then also ported the posterior, robustness, and sequential plot functions to ggplot2. But at that time, the summarystats module also used these functions and I didn't want to also adjust the code in those modules (the PR already was massive). So that's why I added the `2` in `.plotSequentialBF.ttest2` and so on.

**Review by TimKDJ — APPROVED** [review]
I verified that these are indeed not used anymore

**Comment by boutinb** [comment]
Must it be merged for 0.15?

**Comment by AlexanderLyNL** [comment]
I'd like to merge this for 0.16. Is that okay @vandenman and @TimKDJ

**Comment by vandenman** [comment]
@AlexanderLyNL yes that was the plan!

**Pull request merged**
