### PR TITLE
Conditionally add a dependency on the variables

### PR DESCRIPTION
**Pull request by vandenman**
Fixes https://github.com/jasp-stats/jasp-test-release/issues/1222

### CODE REVIEW

**Comment by juliuspf** [comment]
the bug from https://github.com/jasp-stats/jasp-test-release/issues/1222 still persists

**Review by juliuspf — COMMENTED** [review]
the bug from https://github.com/jasp-stats/jasp-test-release/issues/1222 still persists. Is that not the case on your machine?

**Comment by vandenman** [comment]
the issue is fixed on my machine. Are you sure that you checked out the correct branch? Otherwise, you could try deleting `~/Library/Application Support/JASP` and then restart JASP and try again? Also, make sure that you do not start the t-test analysis before installing the module.

**Comment by juliuspf** [comment]
the fix is fine. the problem was with my machine, where the developer module did not properly replace the original module.

**Pull request merged**
