### PR TITLE
Change W to U in Man Whitney test and include some descriptives of ranks

### PR DESCRIPTION
**Pull request by JohnnyDoorn**
Fix https://github.com/jasp-stats/jasp-issues/issues/1735

### CODE REVIEW

**Comment by JohnnyDoorn** [comment]
@boutinb question about the failing i18n check - do I need to put double "%" here to make it pass this test? 
image

**Comment by shun2wang** [comment]
yes for some reasons, and we should use `gettextf(%%)` instead of `gettext(%)`.

**Comment by boutinb** [comment]
> yes for some reasons, and we should use `gettextf("...%%...")` instead of `gettext("...%...")`.

Yes cf. https://github.com/jasp-stats/jasp-desktop/blob/development/Docs/development/jasp-translation-rules.md

**Comment by JohnnyDoorn** [comment]
@shun2wang @boutinb I updated and now the tests pass - can this be merged?

**Review by shun2wang — APPROVED** [review]

**Review by boutinb — APPROVED** [review]

**Pull request merged**
