### PR TITLE
Allow custom CI levels in Bayesian t-tests

### PR DESCRIPTION
**Pull request by Kucharssim**
See https://github.com/jasp-stats/jasp-desktop/pull/4232

Somehow the qml files were not up to date between this repo and `stable`, I think we missed to add some of the changes here (i.e., the Wilcoxon stuff + enabling buttons). This PR will make the two repos consistent.

### CODE REVIEW

**Comment by Kucharssim** [comment]
Is it ok to merge this, let's ask @JorisGoosen ?

**Comment by JorisGoosen** [comment]
Aah well, if that is the case this should definitely be merged!

**Comment by JorisGoosen** [comment]
But maybe you could `git commit --amend` the single commit and add a link to the jasp-desktop + commit you took the code from?
This way we can sort of understand where it is coming from.

After that you can merge it yourself if you'd like ^^

**Comment by Kucharssim** [comment]
> But maybe you could git commit --amend the single commit and add a link to the jasp-desktop + commit you took the code from?

Yes, I will do that.

> After that you can merge it yourself if you'd like ^^

Ok ok, I can, I still have not come to terms with the great power vested in me: It comes with a lot of responsibility 😅

**Pull request merged**
