### PR TITLE
Bayesian t-test uses frequentist data reader

### PR DESCRIPTION
**Pull request by JohnnyDoorn**
Fix https://github.com/jasp-stats/jasp-issues/issues/2102

### CODE REVIEW

**Comment by vandenman** [comment]
The changes look fine but I don't understand why the unit tests fail..., let's see if they also fail in https://github.com/jasp-stats/jaspTTests/pull/262, otherwise, I'll try to reproduce this locally.

**Comment by JohnnyDoorn** [comment]
Its just some rng thing no?

**Comment by vandenman** [comment]
It's the same test on each OS, and the error is the same for macOS and Ubuntu but different on Windows. I just want to make sure it's got nothing to do with the specific stuff for handling ordinal input.

**Comment by vandenman** [comment]
and fix the test if I can :)

**Comment by vandenman** [comment]
https://github.com/jasp-stats/jaspTTests/blob/efccd74f57b82be21bd1678b657db0b36c913419/tests/testthat/test-ttestbayesianindependentsamples.R#L181-L187

Always fun to encounter your past self in some obscure comment somewhere...

**Review by vandenman — APPROVED** [review]

**Comment by JohnnyDoorn** [comment]
Haha awesome, then we get it right for at least 1 OS ^^

**Pull request merged**
