### PR TITLE
UI consistency: 'Effect Size' -> 'Effect size'

### PR DESCRIPTION
**Pull request by vandenman**
As encountered in the teaching stats meeting.

### CODE REVIEW

**Comment by boutinb** [comment]
It would be fine to change also the language files (po files), so that our translators don't have to re-translate...

**Comment by vandenman** [comment]
@boutinb is this what you had in mind?

**Comment by boutinb** [comment]
> @boutinb is this what you had in mind?

Yes! Maybe just remove the capital by Efecto.

**Review by JohnnyDoorn — APPROVED** [review]

**Comment by vandenman** [comment]
@boutinb should we merge this after the two open weblate PRs (#100 and #101) to avoid introducing any merge conflicts in those PRs?

**Pull request merged**
